"""Added name field to User model

Revision ID: 522bc9e5b352
Revises: 
Create Date: 2025-02-16 12:10:57.278432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522bc9e5b352'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint('hello', ['username'])
        batch_op.drop_column('password')
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('phone')
        batch_op.drop_column('username')
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.drop_column('is_admin')


    # ### end Alembic commands ###
